const DistributorsQueryTypes = {
  REST_SINGLE_DISTRIBUTOR: 'REST_DISTRIBUTORS_USER',
  REST_DISTRIBUTORS_SALES: 'REST_DISTRIBUTORS_SALES',
  REST_DISTRIBUTORS_CUSTOMER: 'REST_DISTRIBUTORS_CUSTOMER',
};

export default DistributorsQueryTypes;
