const SalesQueryTypes = {
  REST_SINGLE_SALE: 'REST_SINGLE_SALE',
  REST_PAYMENT_SALE: 'REST_PAYMENT_SALE',
  REST_COLLECTION_SUMMARY: 'REST_COLLECTION_SUMMARY',
  REST_COLLECTION_VISITOR: 'REST_COLLECTION_VISITOR',
};

export default SalesQueryTypes;
